// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ailab_super_app.Data;

#nullable disable

namespace ailab_super_app.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251025220000_AddRfidReaderTable")]
    partial class AddRfidReaderTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // Bu dosya otomatik oluşturulur, manuel düzenleme gerekmez
        }
    }
}
