name: Deploy to Production

on:
  push:
    branches: [ main ]
  workflow_dispatch: # Manuel tetikleme

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Create .env file from secrets
      run: |
        cat > .env << EOF
        # PostgreSQL Configuration
        POSTGRES_DB=${{ secrets.POSTGRES_DB }}
        POSTGRES_USER=${{ secrets.POSTGRES_USER }}
        POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
        POSTGRES_PORT=5432
        
        # ASP.NET Core Configuration
        ASPNETCORE_ENVIRONMENT=${{ secrets.ASPNETCORE_ENVIRONMENT }}
        API_PORT=6161
        
        # JWT Configuration
        JWT_SECRET=${{ secrets.JWT_SECRET }}
        JWT_ISSUER=${{ secrets.JWT_ISSUER }}
        JWT_AUDIENCE=${{ secrets.JWT_AUDIENCE }}
        JWT_ACCESS_TOKEN_EXPIRATION=${{ secrets.JWT_ACCESS_TOKEN_EXPIRATION }}
        JWT_REFRESH_TOKEN_EXPIRATION=${{ secrets.JWT_REFRESH_TOKEN_EXPIRATION }}
        EOF
    
    - name: Deploy to server via SSH
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.SERVER_PORT }}
        script: |
          cd /var/www/ailab-api
          git pull origin main
          docker compose down
          docker compose up -d --build
          docker compose logs --tail=100 api

